version: '3.8'
services:
  nanoblog:
    image: nanoblog
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - shared:/app/Export:rw
  frontend:
    image: nginx:latest
    volumes:
      - ./docker-nginx.conf:/etc/nginx/nginx.conf:ro
      - shared:/usr/share/nginx/html:ro
    ports:
      - "8080:8080"
    depends_on:
      - nanoblog
volumes:
  shared: