version: '3.8'
services:
  nanoblog:
    image: nanoblog
    build:
      context: ../src
      dockerfile: ../docker/Dockerfile
    env_file:
      - .env
    volumes:
      - ./export:/app/Export:rw
      - ./blog-files:/app/BlogFiles:rw
  frontend:
    image: nginx:latest
    volumes:
      - ./docker-nginx.conf:/etc/nginx/nginx.conf:ro
      - ./export:/usr/share/nginx/html:ro
    ports:
      - "8080:8080"
    depends_on:
      - nanoblog