version: '3.8'
services:
  nanoblog:
    image: ghcr.io/its-laika/nanoblog:latest
    # Use this if you want to use your self built version.
    # build:
    #  context: ../NanoBlog
    #  dockerfile: ../docker/Dockerfile
    env_file:
      - .env
    volumes:
      - ./export:/app/Export:rw
      - ./blog-files:/app/BlogFiles:rw
  frontend:
    image: nginx:latest
    volumes:
      - ./docker-nginx.conf:/etc/nginx/nginx.conf:ro
      - ./export:/usr/share/nginx/html:ro
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - nanoblog