global using IConfiguration = NanoBlog.IConfiguration;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.Filters;
global using NanoBlog;
global using NanoBlog.Attributes;
global using NanoBlog.Containers;
global using NanoBlog.Extensions;
global using NanoBlog.Services.Export;
global using NanoBlog.Services.Generation;
global using NanoBlog.Services.MimeTypes;
global using NanoBlog.Services.Posts;
global using System.ComponentModel.DataAnnotations;
global using System.Runtime.InteropServices;
global using System.Text;
global using System.Text.RegularExpressions;
